# 线上配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
server:
  port: 8101
spring:
  application:
    name: xinapi-backend
    cloud:
      nacos:
        discovery:
          server-addr: 192.168.0.144:8848
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xinapi
    username: #
    password: #
  # Redis 配置
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
    password: #
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''

dubbo:
  application:
    name: xinapi-backend
  protocol:
    name: dubbo
    port: -1
  registry:
    id: xinapi-backend
    address: #
